version: "3.0"
services:
  db:
    env_file:
      - postgres-settings.env
    build:
      dockerfile: postgres.Dockerfile
      context: .
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    hostname: gdq-database

  # twitter:
  #   build: .
  #   command: python -m gdq_collector --tracker=twitter --cloudwatch
  #   depends_on:
  #     - db

  timeseries:
    build: .
    command: python -m gdq_collector --tracker=timeseries --cloudwatch
    depends_on:
      - db

  twitch:
    build: .
    command: python -m gdq_collector --tracker=twitch --cloudwatch
    depends_on:
      - db

  schedule:
    build: .
    command: python -m gdq_collector --tracker=schedule --cloudwatch
    depends_on:
      - db

  donations:
    command: python -m gdq_collector --tracker=donations --cloudwatch
    build: .
    depends_on:
      - db

  donation_messages:
    command: python -m gdq_collector --tracker=donation_messages --cloudwatch
    build: .
    depends_on:
      - db
